version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.1
    - 6.2.0
    - 6.2.1
    - 6.2.4
  - dependency-name: strongly-typed-events
    versions:
    - 2.0.9
    - 2.1.5
    - 2.1.6
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.10
    - 7.13.4
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.1
    - 7.13.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.12.7
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 4.5.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
  - dependency-name: "@4site/engrid-common"
    versions:
    - 0.1.14
    - 0.1.16
  - dependency-name: "@4site/engrid-styles"
    versions:
    - 0.1.16
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: ini
    versions:
    - 1.3.8
